# Generated by Django 2.2.4 on 2020-07-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('update_date', models.DateField()),
                ('create_by_id', models.CharField(max_length=7)),
                ('create_by_ip', models.CharField(max_length=15)),
                ('update_by_ip', models.CharField(max_length=15)),
                ('is_visible', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_verified', models.BooleanField()),
                ('is_approved', models.BooleanField()),
                ('is_archived', models.BooleanField()),
                ('is_dormant', models.BooleanField()),
                ('is_so_delete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TFconnector',
            fields=[
                ('status_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tf_connector.Status')),
                ('connector_name', models.CharField(max_length=20)),
                ('connector_value', models.CharField(max_length=500)),
                ('connector_desc', models.CharField(max_length=100)),
                ('connector_remark', models.CharField(max_length=100)),
            ],
            bases=('tf_connector.status',),
        ),
    ]
